billing: main.o customer.o item.o bill.o
	gcc -o billing main.o customer.o item.o bill.o

main.o: main.c
	gcc -c -o main.o main.c

customer.o: customer.c
	gcc -c -o customer.o customer.c

item.o: item.c
	gcc -c -o item.o item.c

bill.o: bill.c
	gcc -c -o bill.o bill.c
